
----------------------user creation  and privilages to user commands----

CREATE USER Hr IDENTIFIED BY pass;

GRANT CONNECT, RESOURCE TO Hr;

SELECT username FROM dba_users WHERE username = 'HR';

ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;
CREATE USER Hr IDENTIFIED BY pass;
GRANT CONNECT, RESOURCE TO Hr;

ALTER USER HR DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;


GRANT CREATE VIEW TO HR;

GRANT CREATE PROCEDURE TO HR;


GRANT CREATE SEQUENCE TO HR;


GRANT CREATE SYNONYM TO HR;


GRANT SELECT ANY TABLE TO HR;


SELECT * FROM USER_SYS_PRIVS;


GRANT DBA TO HR;


GRANT ALL PRIVILEGES TO HR;


REVOKE ALL PRIVILEGES FROM HR;
REVOKE DBA FROM HR;

GRANT CREATE TABLE, CREATE VIEW, CREATE SEQUENCE, CREATE PROCEDURE TO HR;

GRANT SELECT ANY TABLE TO HR;

GRANT DROP ANY TABLE TO HR;

GRANT DROP ANY VIEW TO HR;

GRANT DROP ANY TABLE TO HR;


GRANT DROP ANY VIEW TO HR;
------------------------------------------------------------------------------------------

ALTER SYSTEM KILL SESSION 'sid,serial#' IMMEDIATE;

SPOOL C:\Users\DELL\OneDrive\Documents\output.txt
SELECT * FROM emp;
SPOOL OFF;










